{% set name = "bc-detect-secrets" %}
{% set version = "1.5.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d596aaca3d62165aa0a19318738ec4b74e01eb5791576b909a0dcf2f3550f24e

build:
  entry_points:
    - detect-secrets = detect_secrets.main:main
    - detect-secrets-hook = detect_secrets.pre_commit_hook:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - pyyaml
    - requests
    - unidiff

test:
  imports:
    - detect_secrets
  commands:
    - pip check
    - detect-secrets --help
    - detect-secrets-hook --help
  requires:
    - pip

about:
  home: https://github.com/bridgecrewio/detect-secrets
  summary: Tool for detecting secrets in the codebase
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - borchero
    - nick-harmening
