{% set name = "bc-detect-secrets" %}
{% set version = "1.5.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bc-detect-secrets-{{ version }}.tar.gz
  sha256: ab9ecaa19723559e592c750e0c097ab264050d9508064fd6cee553c73608ee92

build:
  entry_points:
    - detect-secrets = detect_secrets.main:main
    - detect-secrets-hook = detect_secrets.pre_commit_hook:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pyyaml
    - requests
    - unidiff

test:
  imports:
    - detect_secrets
  commands:
    - pip check
    - detect-secrets --help
    - detect-secrets-hook --help
  requires:
    - pip

about:
  home: https://github.com/bridgecrewio/detect-secrets
  summary: Tool for detecting secrets in the codebase
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - borchero
    - nick-harmening
